//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeartFailureReaddminssion.Models.WorkflowTracking
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrackingSampleEntities : DbContext
    {
        public TrackingSampleEntities()
            : base("name=TrackingSampleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityInstanceEventsTable> ActivityInstanceEventsTables { get; set; }
        public virtual DbSet<BookmarkResumptionEventsTable> BookmarkResumptionEventsTables { get; set; }
        public virtual DbSet<CustomTrackingEventsTable> CustomTrackingEventsTables { get; set; }
        public virtual DbSet<ExtendedActivityEventsTable> ExtendedActivityEventsTables { get; set; }
        public virtual DbSet<WorkflowInstanceEventsTable> WorkflowInstanceEventsTables { get; set; }
    }
}
