//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeartFailureReaddminssion.Models.WorkflowTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowInstanceEventsTable
    {
        public int Id { get; set; }
        public System.Guid WorkflowInstanceId { get; set; }
        public string WorkflowActivityDefinition { get; set; }
        public long RecordNumber { get; set; }
        public string State { get; set; }
        public Nullable<byte> TraceLevelId { get; set; }
        public string Reason { get; set; }
        public string ExceptionDetails { get; set; }
        public string SerializedAnnotations { get; set; }
        public System.DateTime TimeCreated { get; set; }
    }
}
